osx_image: xcode7.3
language: objective-c
script:
    - |
      xcodebuild test \
      -project FRDModuleManager.xcodeproj \
      -scheme FRDModuleManagerTests \
      -sdk iphonesimulator \
      ONLY_ACTIVE_ARCH=NO
